name: build

on: [push, pull_request]

jobs:
  android-example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Setup Lyra dependencies
        uses: ./.github/actions/setup-lyra-deps
      - name: Build Android App
        shell: bash
        run: |
          export ANDROID_NDK_HOME="$ANDROID_HOME/ndk/21.4.7075529"
          bazel build lyra/android_example:lyra_android_example --config=android_arm64 --copt=-DBENCHMARK
      - name: Copy artifacts
        shell: bash
        run: |
          mkdir action-product
          cp bazel-bin/lyra/android_example/lyra_android_example.apk action-product/lyra_example.apk
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: lyra-android-example
          path: action-product

  android-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Setup Lyra dependencies
        uses: ./.github/actions/setup-lyra-deps
      - name: Build and upload
        uses: ./.github/actions/lyra-builder
        with:
          platform: android
          architecture: arm64
          build-options: --config=android_arm64

  linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Setup Lyra dependencies
        uses: ./.github/actions/setup-lyra-deps
      - name: Build and upload
        uses: ./.github/actions/lyra-builder
        with:
          platform: linux
          architecture: amd64

  macos-amd64:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Setup Lyra dependencies
        uses: ./.github/actions/setup-lyra-deps
      - name: Build and upload
        uses: ./.github/actions/lyra-builder
        with:
          platform: macos
          architecture: amd64
